class BillingMessagesVO:
    ORDER_NOT_FOUND = "Order not found."
    PAYMENT_NOT_FOUND = "Payment not found."
    RECEIPT_NOT_FOUND = "Payment receipt not found."
    COURSE_ALREADY_PURCHASED = "You already purchased this course."
    ORDER_ALREADY_PAID = "Order is already paid."
    PAYMENT_CREATED = "Payment created successfully."
    PAYMENT_CONFIRMED = "Payment confirmed successfully."
    PAYMENT_CONFIRM_FORBIDDEN = "Only admins can manually confirm this payment."
    RECEIPT_CREATED = "Payment receipt uploaded successfully. Waiting for admin verification."
    RECEIPT_APPROVED = "Payment receipt approved successfully."
    RECEIPT_REJECTED = "Payment receipt rejected."
    RECEIPT_REQUIRED = "Receipt file, receipt URL, or tracking code is required."
    RECEIPT_PROVIDER_NOT_ALLOWED = "Receipt upload is only available for card-to-card payments."
    RECEIPT_ALREADY_PENDING = "A receipt is already waiting for admin verification."
    GATEWAY_VERIFIED = "Gateway payment verification completed."
