from django.conf import settings
from django.db import models
from django.db.models import F, Q
from django.utils.timezone import now

from backend.apps.core_models.entities.base.base import BaseModel


class ReferralCode(BaseModel):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name="referral_code_record",
        on_delete=models.CASCADE,
    )
    code = models.CharField(max_length=16, unique=True, db_index=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [models.Index(fields=["code", "is_active", "is_deleted"], name="referral_code_active_idx")]

    def __str__(self) -> str:
        return f"{self.user_id}:{self.code}"


class ReferralInvite(BaseModel):
    inviter = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="referral_invites_sent",
        on_delete=models.PROTECT,
    )
    invitee = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name="referral_invite_received",
        on_delete=models.CASCADE,
    )
    referral_code = models.ForeignKey(
        ReferralCode,
        related_name="invites",
        on_delete=models.PROTECT,
    )
    registered_at = models.DateTimeField(default=now)

    class Meta:
        ordering = ["-registered_at"]
        constraints = [
            models.CheckConstraint(condition=~Q(inviter=F("invitee")), name="referral_inviter_not_invitee"),
        ]
        indexes = [
            models.Index(fields=["inviter", "registered_at"], name="referral_inviter_date_idx"),
        ]

    def __str__(self) -> str:
        return f"{self.inviter_id}->{self.invitee_id}"


class TelegramChannelReferralLink(BaseModel):
    """One Telegram channel invite link owned by one website account.

    The invite link is generated by the configured Telegram bot, not by the
    website user. A unique owner/channel constraint keeps link generation
    idempotent across the web panel and Telegram bot.
    """

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="telegram_channel_referral_links",
        on_delete=models.PROTECT,
    )
    channel_username = models.CharField(max_length=64)
    channel_chat_id = models.CharField(max_length=64, blank=True, default="")
    invite_link = models.URLField(max_length=512, unique=True)
    telegram_name = models.CharField(max_length=32, blank=True, default="")
    is_revoked = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["owner", "channel_username"],
                name="ref_chlink_owner_uniq",
            ),
        ]
        indexes = [
            models.Index(
                fields=["owner", "channel_username", "is_revoked"],
                name="ref_chlink_owner_idx",
            ),
        ]

    def __str__(self) -> str:
        return f"{self.owner_id}:{self.channel_username}"


class TelegramChannelReferralMember(BaseModel):
    """First-observed membership ledger for referral attribution.

    One Telegram account gets exactly one ledger row per channel. The
    ``referral_link`` is only assigned on the very first observed join. It is
    never replaced on re-join, which guarantees that leave/rejoin cycles cannot
    increase another user's referral count.
    """

    channel_username = models.CharField(max_length=64)
    channel_chat_id = models.CharField(max_length=64, blank=True, default="")
    telegram_user_id = models.BigIntegerField()
    username = models.CharField(max_length=150, blank=True, default="")
    first_name = models.CharField(max_length=150, blank=True, default="")
    last_name = models.CharField(max_length=150, blank=True, default="")
    referral_link = models.ForeignKey(
        TelegramChannelReferralLink,
        related_name="members",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )
    first_joined_at = models.DateTimeField(null=True, blank=True)
    last_joined_at = models.DateTimeField(null=True, blank=True)
    left_at = models.DateTimeField(null=True, blank=True)
    is_current_member = models.BooleanField(default=False)

    class Meta:
        ordering = ["-first_joined_at", "-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["channel_username", "telegram_user_id"],
                name="ref_chmem_user_uniq",
            ),
        ]
        indexes = [
            models.Index(
                fields=["referral_link", "first_joined_at"],
                name="ref_chmem_link_idx",
            ),
            models.Index(
                fields=["channel_username", "is_current_member"],
                name="ref_chmem_state_idx",
            ),
        ]

    def __str__(self) -> str:
        return f"{self.channel_username}:{self.telegram_user_id}"
