# Generated by Django 4.2.3 on 2025-09-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_access_user_updated_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tokenblacklist",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
