# Generated by Django 4.2.3 on 2025-09-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="symbol",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
