from __future__ import annotations

from typing import Any, Protocol


class CommerceBotLogicInterface(Protocol):
    """Contract consumed by TelegramBotService.

    A new domain such as gym plans/classes can implement this contract and be
    injected into TelegramBotService without changing Telegram conversation
    orchestration. Keep model-specific queries inside the domain logic and
    adapter, not inside services.py.
    """

    def list_courses(self, *, page: int, page_size: int) -> tuple[list[Any], bool]: ...
    def get_course(self, course_id_or_slug: str) -> Any: ...
    def list_reviews(self, course_id: Any, *, limit: int) -> list[Any]: ...
    def checkout_course(self, *, user: Any, course_id: str) -> tuple[Any, Any, bool]: ...
    def list_enrollments(self, user: Any, *, limit: int) -> list[Any]: ...
    def list_orders(self, user: Any, *, limit: int) -> list[Any]: ...
    def submit_review(self, *, user: Any, course_id: str, rating: int, title: str, comment: str) -> Any: ...
    def list_pending_reviews(self, *, limit: int) -> list[Any]: ...
    def moderate_review(self, *, admin_user: Any, review_id: str, status: str, admin_note: str = "") -> Any: ...
    def upload_payment_receipt(self, *, user: Any, payment_id: str, tracking_code: str = "", file_id: str = "", file_type: str = "", original_file_name: str = "", note: str = "") -> Any: ...
    def list_pending_payment_receipts(self, *, limit: int) -> list[Any]: ...
    def review_payment_receipt(self, *, admin_user: Any, receipt_id: str, status: str, admin_note: str = "") -> Any: ...
    def create_course(self, *, admin_user: Any, title: str, short_description: str, description: str, price: Any, currency: str, duration_minutes: int, level: str, publish: bool) -> Any: ...
    def list_admin_courses(self, *, page: int, page_size: int) -> tuple[list[Any], bool]: ...
    def get_admin_course(self, course_id_or_slug: str) -> Any: ...
    def update_course_status(self, *, admin_user: Any, course_id: str, status: str) -> Any: ...
    def update_course_field(self, *, admin_user: Any, course_id: str, field: str, value: Any) -> Any: ...
    def delete_course(self, *, admin_user: Any, course_id: str) -> Any: ...
    def create_lesson(self, *, admin_user: Any, course_id: str, title: str, description: str, content: str, video_url: str, duration_minutes: int, position: int | None, is_preview: bool) -> Any: ...
