# Generated by Django 5.2.9 on 2026-06-30 15:50
# Patched to be safe for databases where one of the old index names does not exist.

from django.db import migrations


INDEX_RENAMES = [
    {
        "table": "telegram_bot_channelsyncmessage",
        "old_name": "telegram_bo_source__6afdc3_idx",
        "new_name": "telegram_bo_source__7c9aaf_idx",
        "columns": ["source_provider", "source_chat_id", "source_message_id"],
    },
    {
        "table": "telegram_bot_channelsyncmessage",
        "old_name": "telegram_bo_target__287c1b_idx",
        "new_name": "telegram_bo_target__f12eff_idx",
        "columns": ["target_provider", "target_chat_id", "target_message_id"],
    },
    {
        "table": "telegram_bot_telegramprofile",
        "old_name": "telegram_bo_msg_prov_chat_idx",
        "new_name": "telegram_bo_messeng_39538d_idx",
        "columns": ["messenger_provider", "chat_id"],
    },
]


def _index_exists(connection, table_name, index_name):
    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, table_name)
    return index_name in constraints


def _create_index_if_missing(schema_editor, table_name, index_name, columns):
    quoted_table = schema_editor.quote_name(table_name)
    quoted_index = schema_editor.quote_name(index_name)
    quoted_columns = ", ".join(schema_editor.quote_name(column) for column in columns)
    schema_editor.execute(
        f"CREATE INDEX IF NOT EXISTS {quoted_index} ON {quoted_table} ({quoted_columns})"
    )


def _safe_rename_or_create_indexes(apps, schema_editor):
    connection = schema_editor.connection

    # This project uses PostgreSQL in production/local development. For other
    # backends, keep the Django migration state update below and avoid executing
    # backend-specific ALTER INDEX SQL.
    if connection.vendor != "postgresql":
        return

    for item in INDEX_RENAMES:
        table_name = item["table"]
        old_name = item["old_name"]
        new_name = item["new_name"]
        columns = item["columns"]

        old_exists = _index_exists(connection, table_name, old_name)
        new_exists = _index_exists(connection, table_name, new_name)

        if new_exists:
            continue

        if old_exists:
            schema_editor.execute(
                f"ALTER INDEX {schema_editor.quote_name(old_name)} "
                f"RENAME TO {schema_editor.quote_name(new_name)}"
            )
            continue

        # Some databases created from older/manual migrations do not have the old
        # index name, so RenameIndex fails with UndefinedTable. Create the index
        # with the expected final name to keep DB schema and Django state aligned.
        _create_index_if_missing(schema_editor, table_name, new_name, columns)


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0006_channel_sync_message"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_safe_rename_or_create_indexes, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="channelsyncmessage",
                    new_name="telegram_bo_source__7c9aaf_idx",
                    old_name="telegram_bo_source__6afdc3_idx",
                ),
                migrations.RenameIndex(
                    model_name="channelsyncmessage",
                    new_name="telegram_bo_target__f12eff_idx",
                    old_name="telegram_bo_target__287c1b_idx",
                ),
                migrations.RenameIndex(
                    model_name="telegramprofile",
                    new_name="telegram_bo_messeng_39538d_idx",
                    old_name="telegram_bo_msg_prov_chat_idx",
                ),
            ],
        ),
    ]
