# Generated by Django 4.2.3 on 2025-09-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_role",
                to="accounts.role",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="accesses",
            field=models.ManyToManyField(
                default=None, related_name="access_roles", to="accounts.access"
            ),
        ),
    ]
