# Generated by Django 4.2.3 on 2025-09-09 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_role_alter_role_accesses"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="created_verified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_code",
            field=models.IntegerField(null=True),
        ),
    ]
