# Generated by Django 5.2.9 on 2026-06-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_role_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='access',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='tokenblacklist',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
