# Generated by ChatGPT on 2026-07-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_apikeymanagermodel_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfigModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('singleton_key', models.CharField(default='default', max_length=64, unique=True)),
                ('name', models.CharField(default='Project', max_length=120)),
                ('display_name', models.CharField(default='Project', max_length=120)),
                ('slug', models.SlugField(default='project', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('tagline', models.CharField(blank=True, default='مسیر یادگیری برنامه نویسی از مقدماتی تا ورود به بازارکار', max_length=255)),
                ('email_domain', models.CharField(blank=True, default='example.com', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=255)),
                ('support_email', models.EmailField(blank=True, default='', max_length=255)),
                ('sales_email', models.EmailField(blank=True, default='', max_length=255)),
                ('partnership_email', models.EmailField(blank=True, default='', max_length=255)),
                ('github_url', models.URLField(blank=True, default='#', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='#', max_length=500)),
                ('telegram_url', models.URLField(blank=True, default='#', max_length=500)),
                ('instagram_url', models.URLField(blank=True, default='#', max_length=500)),
                ('phone', models.CharField(blank=True, default='+98 9123456789', max_length=50)),
                ('address', models.CharField(blank=True, default='ایران، تهران', max_length=500)),
                ('working_hours', models.CharField(blank=True, default='شنبه تا چهارشنبه، 9:00 تا 18:00', max_length=255)),
                ('user_created_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project config',
                'verbose_name_plural': 'Project config',
            },
        ),
    ]
