# Generated by Django 5.2.9 on 2026-06-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeymanagermodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
