# Generated by Django 5.2.9 on 2026-07-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_rebrand_project_to_devixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfigmodel',
            name='display_name',
            field=models.CharField(default='Devixa', max_length=120),
        ),
        migrations.AlterField(
            model_name='projectconfigmodel',
            name='email_domain',
            field=models.CharField(blank=True, default='acdevixa.ir', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectconfigmodel',
            name='name',
            field=models.CharField(default='devixa', max_length=120),
        ),
        migrations.AlterField(
            model_name='projectconfigmodel',
            name='slug',
            field=models.SlugField(default='devixa', max_length=120),
        ),
    ]
