# Generated by Django 5.2.9 on 2026-06-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telegramprofile',
            new_name='telegram_bo_telegra_9ead8b_idx',
            old_name='telegram_bo_telegr_0ab58f_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramprofile',
            new_name='telegram_bo_chat_id_123572_idx',
            old_name='telegram_bo_chat_i_fb4007_idx',
        ),
    ]
