# Generated by Django 5.2.9 on 2026-06-14 12:44
# Patched to be safe for databases where old index names were not created.

from django.db import migrations


INDEX_RENAMES = [
    {
        "table": "telegram_bot_telegramprofile",
        "old_name": "telegram_bo_telegr_0ab58f_idx",
        "new_name": "telegram_bo_telegra_9ead8b_idx",
        "columns": ["telegram_user_id"],
    },
    {
        "table": "telegram_bot_telegramprofile",
        "old_name": "telegram_bo_chat_i_fb4007_idx",
        "new_name": "telegram_bo_chat_id_123572_idx",
        "columns": ["chat_id"],
    },
]


def _index_exists(connection, table_name, index_name):
    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, table_name)
    return index_name in constraints


def _create_index_if_missing(schema_editor, table_name, index_name, columns):
    quoted_table = schema_editor.quote_name(table_name)
    quoted_index = schema_editor.quote_name(index_name)
    quoted_columns = ", ".join(schema_editor.quote_name(column) for column in columns)
    schema_editor.execute(
        f"CREATE INDEX IF NOT EXISTS {quoted_index} ON {quoted_table} ({quoted_columns})"
    )


def _safe_rename_or_create_indexes(apps, schema_editor):
    connection = schema_editor.connection

    if connection.vendor != "postgresql":
        return

    for item in INDEX_RENAMES:
        table_name = item["table"]
        old_name = item["old_name"]
        new_name = item["new_name"]
        columns = item["columns"]

        old_exists = _index_exists(connection, table_name, old_name)
        new_exists = _index_exists(connection, table_name, new_name)

        if new_exists:
            continue

        if old_exists:
            schema_editor.execute(
                f"ALTER INDEX {schema_editor.quote_name(old_name)} "
                f"RENAME TO {schema_editor.quote_name(new_name)}"
            )
            continue

        _create_index_if_missing(schema_editor, table_name, new_name, columns)


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_safe_rename_or_create_indexes, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="telegramprofile",
                    new_name="telegram_bo_telegra_9ead8b_idx",
                    old_name="telegram_bo_telegr_0ab58f_idx",
                ),
                migrations.RenameIndex(
                    model_name="telegramprofile",
                    new_name="telegram_bo_chat_id_123572_idx",
                    old_name="telegram_bo_chat_i_fb4007_idx",
                ),
            ],
        ),
    ]
