# Generated by assistant for channel sync support.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0005_rubika_support_chat_ids_as_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelSyncMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_provider", models.CharField(db_index=True, default="telegram", max_length=30)),
                ("source_chat_id", models.CharField(db_index=True, max_length=160)),
                ("source_message_id", models.CharField(db_index=True, max_length=160)),
                ("target_provider", models.CharField(db_index=True, max_length=30)),
                ("target_chat_id", models.CharField(db_index=True, max_length=160)),
                ("target_message_id", models.CharField(blank=True, db_index=True, max_length=160)),
                ("text_hash", models.CharField(blank=True, max_length=64)),
                ("last_error", models.TextField(blank=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="channelsyncmessage",
            index=models.Index(fields=["source_provider", "source_chat_id", "source_message_id"], name="telegram_bo_source__6afdc3_idx"),
        ),
        migrations.AddIndex(
            model_name="channelsyncmessage",
            index=models.Index(fields=["target_provider", "target_chat_id", "target_message_id"], name="telegram_bo_target__287c1b_idx"),
        ),
        migrations.AddConstraint(
            model_name="channelsyncmessage",
            constraint=models.UniqueConstraint(fields=("source_provider", "source_chat_id", "source_message_id", "target_provider", "target_chat_id"), name="unique_channel_sync_source_target"),
        ),
    ]
