# Generated by Django 5.2.9 on 2026-06-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_channel_sync_message'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channelsyncmessage',
            new_name='telegram_bo_source__7c9aaf_idx',
            old_name='telegram_bo_source__6afdc3_idx',
        ),
        migrations.RenameIndex(
            model_name='channelsyncmessage',
            new_name='telegram_bo_target__f12eff_idx',
            old_name='telegram_bo_target__287c1b_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramprofile',
            new_name='telegram_bo_messeng_39538d_idx',
            old_name='telegram_bo_msg_prov_chat_idx',
        ),
    ]
