# Generated by Django 5.2.9 on 2026-07-02 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0009_support_and_scheduled_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telegramprofile',
            index=models.Index(fields=['chat_id'], name='telegram_bo_chat_id_123572_idx'),
        ),
    ]
