from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from backend.apps.common.web.assets.value_objects.asset_bundle_vo import (
    AssetBundleDefinition,
    AssetKind,
)


@dataclass(frozen=True, slots=True)
class BuiltAssetBundle:
    name: str
    output_path: Path
    source_count: int
    size_bytes: int


class AssetBundleLogic:
    """Build deterministic bundles while keeping source assets authoritative."""

    def __init__(self, static_root: Path) -> None:
        self._static_root = static_root.resolve()

    def build(self, definition: AssetBundleDefinition) -> BuiltAssetBundle:
        output_path = self._resolve(definition.output_relative_path)
        chunks = [self._read_source(path) for path in definition.source_relative_paths]
        content = self._join(definition, chunks)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8", newline="\n")

        return BuiltAssetBundle(
            name=definition.name,
            output_path=output_path,
            source_count=len(chunks),
            size_bytes=output_path.stat().st_size,
        )

    def _read_source(self, relative_path: str) -> tuple[str, str]:
        source_path = self._resolve(relative_path)
        if not source_path.is_file():
            raise FileNotFoundError(f"Asset source does not exist: {source_path}")
        return relative_path, source_path.read_text(encoding="utf-8")

    def _resolve(self, relative_path: str) -> Path:
        resolved = (self._static_root / relative_path).resolve()
        if self._static_root not in resolved.parents and resolved != self._static_root:
            raise ValueError(f"Asset path escapes static root: {relative_path}")
        return resolved

    @staticmethod
    def _join(
        definition: AssetBundleDefinition,
        chunks: list[tuple[str, str]],
    ) -> str:
        separator = "\n\n"
        rendered: list[str] = [
            "/* Generated by build_frontend_assets. Edit source files, not this bundle. */"
            if definition.kind == AssetKind.CSS
            else "// Generated by build_frontend_assets. Edit source files, not this bundle."
        ]

        for relative_path, content in chunks:
            marker = (
                f"/* Source: {relative_path} */"
                if definition.kind == AssetKind.CSS
                else f"// Source: {relative_path}"
            )
            normalized = content.replace("\r\n", "\n").strip()
            if definition.kind == AssetKind.CSS:
                normalized = normalized.replace('@charset "UTF-8";', "")
            rendered.extend((marker, normalized))

        return separator.join(rendered).rstrip() + "\n"
